In [42]:
pip install preprocessing

In [39]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                       [-1.5, 2.4, 3.5],
                       [0.5, -7.9, 5.6],
                       [5.9, 2.3, -5.8]])
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [35]:
sample_data.shape

(4, 3)

In [36]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [40]:
preprocessing = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessing.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [41]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)

scaled_data = preprocessor.transform(sample_data)
scaled_data

AttributeError: ignored

In [15]:
l1_normalisasi_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalisasi_data

AttributeError: ignored

In [16]:
l1_normalisasi_data = preprocessing.normalize(sample_data, norm='l2')
l1_normalisasi_data

AttributeError: ignored

In [17]:
label_kategori = ['senin','selasa','rabu','kamis','jumat','sabtu','minggu']
encoder = preprocessing.LabelEncoder()
encoder.fit(label_kategori)

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
  print(item, '=', i)


AttributeError: ignored

In [18]:
test_labels = ['senin','selasa','jumat']
encoded_values = encoder.transform(test_labels)
print("labels = ", test_labels)
peint("Encoded values = ", list(encoded_values))

NameError: ignored